version: '3'

services:
  db:
    container_name: souls
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: kiew
      POSTGRES_PASSWORD: kiew
      POSTGRES_DB: souls
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "7320:5432"

  zookeeper:
    container_name: zookeeper
    image: 'zookeeper:3.4'
    ports:
      - '2181:2181'
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:3'
    ports:
      - '9092:9092'
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    container_name: control-center
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:9092
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONTROL_CENTER_KAFKA_CLUSTER_ID: "kafka-cluster"
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_INTERNAL_TOPICS_REPLICATION: 1
      CONTROL_CENTER_REPLICATION_FACTOR: 1